suppressPackageStartupMessages({
  library(yaml)
  library(tidyr)
  library(arrow)
  library(dplyr)
  library(multidplyr)
  library(purrr)
  library(forecast)
  library(multidplyr)
  library(parallel)
  library(R.utils)
  library(readr)
  library(ggplot2)
  library(sjmisc)
  library(viridis)
  library(foreach)
  library(doParallel)
  library(fpCompare)
})

source("R/read_data.R")
source("R/forecast.R")
source("R/forecast_utils.R")
source("R/plots.R")
source("R/tables.R")
source("R/evaluation_utils.R")

set.seed(789)
